### PR TITLE
Bump package version in preparation for release

### PR DESCRIPTION
**Pull request by H-Shay**
As the title states.

### CODE REVIEW

**Comment by H-Shay** [comment]
Anything else that needs to be changed for the release? I didn't see any instructions anywhere - my plan is to merge this PR, tag it, then create a release on Github. Looks like there is a Github Actions to build and push the new release as well...

**Review by turt2live — APPROVED** [review]
I think this is correct. For the github release, there's an "Automatically generate changelog" button we should make use of.

Separately, we should also prepare documentation like [this](https://github.com/matrix-org/matrix-spec/blob/main/meta/releasing.md#prerequisites--preparation) so we know how to do this again 😅

**Comment by H-Shay** [comment]
Merged #498 into main.

**Comment by H-Shay** [comment]
Merged #498 into main.

**Comment by H-Shay** [comment]
Irritatingly it looks like the package version was not increased when the last release was made and the version should actually be 1.6.5 (as the current Github release is 1.6.4). PR to fix that here: https://github.com/matrix-org/mjolnir/pull/499

**Pull request merged**
