### PR TITLE
Replace shutdown_room API with delete_room

### PR DESCRIPTION
**Pull request by dklimpel**
Fixes: #76

I am was not sure how to do the local unit tests.
I hope it helps to fix the issue.

Signed-off-by: Dirk Klimpel <dirk@klimpel.org>

### CODE REVIEW

**Comment by Yoric** [comment]
If I [read the documentation correctly](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/rooms.md#delete-room-api), the API we need to use is `DELETE /_synapse/admin/v1/rooms/<room_id>`, which isn't the API used in this patch.

**Comment by dklimpel** [comment]
The reason is, that the patch is older than the last changes at the API.

**Comment by Yoric** [comment]
> The reason is, that the patch is older than the last changes at the API.

That makes sense :)

**Comment by dklimpel** [comment]
I close it in preference to #117

**Pull request closed without merging**
