### PR TITLE
Change antispam Python module verison with mjolnir version.

### PR DESCRIPTION
**Pull request by Gnuxie**
The reason we want this is so that people do not forget to change the verison number in the synapse module.
The precedent is that the version number has been 0.1.0 since the begging until now.
While this solution does mean that there may be new version of the module where
nothing has actually changed, this is still better than not changing the version at all.
Another version scheme for the module would be inconsistent to
the git repository tags and that has the potential to cause much more confusion
than "blank" version bumps.
If this is a problem, then antispam must be extracted to another repository.

In order to test this, run `yarn version --patch` observe the changes with `git log` and `git diff HEAD~`,
then YOU MUST delete the tag with `git tag --delete vd.d.d` when you are finished.

https://classic.yarnpkg.com/en/docs/cli/version

### CODE REVIEW

**Review by jesopo — APPROVED** [review]
looks good to me, and works correctly:

```diff
✨ ~/src/matrix-org/mjolnir gnuxie/yarn-version % git show HEAD 
commit 0fdfd614f61ac4df5cc1e20e202cc316f41319bc (HEAD -> gnuxie/yarn-version, tag: v1.4.2)
Author: jesopo <github@lolnerd.net>
Date:   Fri Mar 25 13:26:47 2022 +0000

    v1.4.2

diff --git a/package.json b/package.json
index bc58a16..0fe41f5 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
   "name": "mjolnir",
-  "version": "1.4.1",
+  "version": "1.4.2",
   "description": "A moderation tool for Matrix",
   "main": "lib/index.js",
   "repository": "git@github.com:matrix-org/mjolnir.git",
diff --git a/synapse_antispam/setup.py b/synapse_antispam/setup.py
index ad0b4f1..91544b7 100644
--- a/synapse_antispam/setup.py
+++ b/synapse_antispam/setup.py
@@ -2,7 +2,7 @@ from setuptools import setup, find_packages
 
 setup(
     name="mjolnir",
-    version="0.1.0",
+    version="1.4.2",
     packages=find_packages(),
     description="Mjolnir Antispam",
     include_package_data=True,
```

**Review by Yoric — COMMENTED** [review]
If I understand correctly, with this change, `yarn version` becomes somehow an install step? Who is expected to run that step?

I suspect that this should rather be a git hook of some kind.

**Comment by Gnuxie** [comment]
> becomes somehow an install step? Who is expected to run that step?

Nope

The only people who run `yarn version` is us when releasing a new version, that script already exists in [yarn](https://classic.yarnpkg.com/en/docs/cli/version) and is already used. This is a hook for when that script is run to make sure the python module version matches the version in `package.json` (the hook gets given it as an environment variable `npm_package_version` )

**Comment by Yoric** [comment]
So what's the benefit of doing this vs. reading the npm package version from setup.py?

**Comment by Gnuxie** [comment]
@Yoric the version in setup.py has never been changed by anyone, and this is causing problems for deployment of the module. This PR edits the version number inside setup.py to match the npm package version whenever a mjolnir maintainer runs `yarn version` which they already must do as part of releasing a new version of Mjolnir.

**Review by Yoric — APPROVED** [review]

**Pull request merged**
