### PR TITLE
Fix block_usernames config option

### LINKED ISSUE #244: Antispam: check_username_as_spam marks all users as spammy when `block_usernames` is False.
Introduced in https://github.com/matrix-org/mjolnir/pull/34, so Mjolnir [v0.1.12](https://github.com/matrix-org/mjolnir/releases/tag/v0.1.12). I will PR a fix shortly.

### PR DESCRIPTION
**Pull request by DMRobertson**
Fixes #244.

We've made the same (unfortunate) mistake before in https://github.com/matrix-org/message_limit/commit/a6e4709a843daa30cce5f7a1c7d1dbc96753d221; see also https://github.com/matrix-org/synapse/commit/73fc4887834b33afaf23ff48a68772f8ef9b924c.

### CODE REVIEW

**Review by Gnuxie — APPROVED** [review]
Thanks, is anything else being done about this in Synapse? I don't feel very confident that the explanation and improvements to documentation will stop this from happening again :/

**Comment by DMRobertson** [comment]
> Thanks, is anything else being done about this in Synapse? I don't feel very confident that the explanation and improvements to documentation will stop this from happening again :/

I think I'll defer to @babolivier on that one.

**Comment by jesopo** [comment]
I did have an idea about how to fix this more intuitively; if these functions could be instead returning an enum like `Action.BLOCK`, you'd never have to read the function name to figure out what the return is doing

**Comment by DMRobertson** [comment]
> I did have an idea about how to fix this more intuitively; if these functions could be instead returning an enum like `Action.BLOCK`, you'd never have to read the function name to figure out what the return is doing

Agreed; the difficulty will be doing that in a backwards compatible manner.

**Comment by Gnuxie** [comment]
@DMRobertson are you unable to merge this or is there something else you're waiting on?

**Comment by DMRobertson** [comment]
@Gnuxie not waiting on anything; was just politely deferring to T&S as the owners of this repo. I can press the button now.

**Pull request merged**
